/**
 * QIF Cortical Data — loads fsaverage5 face-band mapping for QifBrainViewer.
 *
 * Assets generated by: src/scripts/generate-cortical-mesh.py
 * Face-band LUT: src/site/models/qif-face-bands.bin (uint8, one byte per face)
 * Metadata: datalake/qif-cortical-mapping.json
 */

import corticalMapping from '../../datalake/qif-cortical-mapping.json';
import { HOURGLASS_BANDS } from './qif-constants';

// ═══ Types ═══

export type CorticalBandId = 'N7' | 'N6';

export interface CorticalMapping {
  totalFaces: number;
  totalVertices: number;
  facesPerHemisphere: number;
  verticesPerHemisphere: number;
  bandIndex: Record<CorticalBandId, number>;
}

// ═══ Static metadata (build-time) ═══

const meta = corticalMapping._metadata;

export const CORTICAL_MAPPING: CorticalMapping = {
  totalFaces: meta.total_faces,
  totalVertices: meta.total_vertices,
  facesPerHemisphere: meta.faces_per_hemisphere,
  verticesPerHemisphere: meta.vertices_per_hemisphere,
  bandIndex: meta.band_index as Record<CorticalBandId, number>,
};

export const FACE_STATS = corticalMapping.face_stats;

// ═══ Band colors (from HOURGLASS_BANDS, resolved for cortical use) ═══

/** Hex color for each cortical QIF band */
export const CORTICAL_BAND_COLORS: Record<CorticalBandId, string> = {
  N7: HOURGLASS_BANDS[0].color, // #166534
  N6: HOURGLASS_BANDS[1].color, // #3a7d44
};

/** Band index (uint8 in LUT) → band ID */
export function bandIndexToId(index: number): CorticalBandId {
  return index === 1 ? 'N6' : 'N7';
}

// ═══ Runtime data loading ═══

let cachedFaceBands: Uint8Array | null = null;

/**
 * Load the per-face band LUT from the binary file.
 * Cached after first load — safe to call multiple times.
 */
export async function loadFaceBands(): Promise<Uint8Array> {
  if (cachedFaceBands) return cachedFaceBands;

  const response = await fetch('/models/qif-face-bands.bin');
  if (!response.ok) {
    throw new Error(`Failed to load face-band LUT: ${response.status}`);
  }

  const buffer = await response.arrayBuffer();
  cachedFaceBands = new Uint8Array(buffer);

  if (cachedFaceBands.length !== CORTICAL_MAPPING.totalFaces) {
    throw new Error(
      `Face-band LUT size mismatch: got ${cachedFaceBands.length}, ` +
      `expected ${CORTICAL_MAPPING.totalFaces}`
    );
  }

  return cachedFaceBands;
}

/**
 * Load inflated vertex positions from binary file.
 * Returns Float32Array of shape (totalVertices * 3).
 */
export async function loadInflatedPositions(): Promise<Float32Array> {
  const response = await fetch('/models/fsaverage5-inflated.bin');
  if (!response.ok) {
    throw new Error(`Failed to load inflated positions: ${response.status}`);
  }

  const buffer = await response.arrayBuffer();
  return new Float32Array(buffer);
}

/** Get the QIF band ID for a given face index. Requires loadFaceBands() first. */
export function getBandForFace(faceIndex: number): CorticalBandId | null {
  if (!cachedFaceBands || faceIndex < 0 || faceIndex >= cachedFaceBands.length) {
    return null;
  }
  return bandIndexToId(cachedFaceBands[faceIndex]);
}

/** Get all face indices belonging to a given band. Requires loadFaceBands() first. */
export function getFacesForBand(bandId: CorticalBandId): number[] {
  if (!cachedFaceBands) return [];
  const targetIndex = CORTICAL_MAPPING.bandIndex[bandId];
  const faces: number[] = [];
  for (let i = 0; i < cachedFaceBands.length; i++) {
    if (cachedFaceBands[i] === targetIndex) {
      faces.push(i);
    }
  }
  return faces;
}
