"""Command line: fetch, evidence, build, buildability, register. Run through atlas_build.py."""
from __future__ import annotations

import argparse
import json
import os
import pathlib
import subprocess
import sys
from typing import Any

from . import build, evidence, fetch, manifest, outputs, overlap, registration, sources
from .errors import PipelineError

DEFAULT_CACHE = pathlib.Path.home() / ".cache" / "qinnovate-atlas"
ASSET_DIR = sources.REPO_ROOT / "src" / "site" / "atlas-assets"
EVIDENCE_PATH = sources.PIPELINE_DIR / "evidence" / "registration-evidence.json"
REPORT_PATH = sources.PIPELINE_DIR / "evidence" / "build-report.json"
BUILDABILITY_PATH = sources.PIPELINE_DIR / "registry" / "buildability.json"


def cache_dir() -> pathlib.Path:
    return pathlib.Path(os.environ.get("ATLAS_CACHE_DIR", str(DEFAULT_CACHE))).expanduser().resolve()


def planned_sources(registry: sources.Registry) -> list[str]:
    """Sources to fetch: every buildable asset source, and both ends of each transform when cleared as inputs."""
    wanted = [plan["source"] for plan in registry.inputs["assets"] if sources.is_buildable(registry, plan["source"])]
    for transform in registry.inputs["transforms"].values():
        wanted += [source_id for source_id in (transform["moving_source"], transform["fixed_source"]) if sources.is_usable_input(registry, source_id)]
    return list(dict.fromkeys(wanted))


def command_fetch(registry: sources.Registry) -> int:
    for source_id in planned_sources(registry):
        print(source_id, fetch.fetch_source(registry, source_id, cache_dir()))
    return 0


def command_evidence(registry: sources.Registry) -> int:
    command_fetch(registry)
    document = {
        "note": "Generated by the atlas pipeline's evidence command. Measures here do not depend on what the registration optimises.",
        "registration": evidence.registration_evidence(cache_dir(), registry),
        "folding": evidence.folding_evidence(cache_dir(), registry),
        "shift_scans": evidence.shift_scan_evidence(cache_dir(), registry, registry.inputs["shift_scan_images"]),
        "cross_source": evidence.cross_source_evidence(cache_dir(), registry),
    }
    manifest.write_json(EVIDENCE_PATH, document)
    print("wrote", EVIDENCE_PATH.relative_to(sources.REPO_ROOT))
    return 0


def pipeline_tree_is_dirty() -> bool:
    """Uncommitted changes to the pipeline's code or inputs. Its own outputs under evidence/ do not count."""
    result = subprocess.run(["git", "-C", str(sources.REPO_ROOT), "status", "--porcelain", "--", "src/scripts/atlas-pipeline",
                             ":(exclude)src/scripts/atlas-pipeline/evidence", "datalake/qif-anatomy-sources.json",
                             "datalake/qif-anatomy-verdicts.json"], capture_output=True, text=True, check=True)
    return bool(result.stdout.strip())


def command_build(registry: sources.Registry, allow_dirty: bool, sheets: bool) -> int:
    if pipeline_tree_is_dirty() and not allow_dirty:
        raise PipelineError("the pipeline or its registry has uncommitted changes; commit them first so the code hash in the manifest names a real state")
    command_fetch(registry)
    recorded: dict[str, Any] | None = json.loads(EVIDENCE_PATH.read_text(encoding="utf-8")) if EVIDENCE_PATH.is_file() else None
    box = build.template_box(cache_dir(), registry)
    allen_cache: dict[str, Any] = {}
    built, skipped = [], {}
    for plan in registry.inputs["assets"]:
        if not sources.is_buildable(registry, plan["source"]):
            skipped[plan["id"]] = sources.buildability_table(registry)[plan["source"]]
            continue
        built.append(build.build_asset(cache_dir(), registry, plan, box, allen_cache))
        print("built", plan["id"], len(built[-1].glb), "bytes", sum(node["vertex_count"] > 0 for node in built[-1].nodes), "meshes")
    overlaps = overlap.cross_atlas_overlaps(built)
    duplicates = [row for row in overlaps if row["duplicate"]]
    if duplicates:
        raise PipelineError(f"the same structure is drawn from two atlases: {duplicates[:3]}; remove one from the build plan")
    document = outputs.write_assets(ASSET_DIR, registry, built, recorded)
    report = {"note": "Generated by the atlas pipeline's build command: per-structure measurements the manifest has no field for.",
              "total_asset_bytes": sum(asset["bytes"] for asset in document["assets"]), "skipped_assets": skipped, "cross_atlas_overlaps": overlaps,
              "assets": {item.plan["id"]: item.report for item in built}}
    manifest.write_json(REPORT_PATH, report)
    if sheets:
        print("review sheets:", outputs.write_review_sheets(cache_dir() / "review", cache_dir(), registry, built))
    print("total asset bytes:", report["total_asset_bytes"])
    return 0


def command_buildability(registry: sources.Registry) -> int:
    manifest.write_json(BUILDABILITY_PATH, {"note": "Blockers per source from the pipeline's buildability rule; an empty list means buildable. "
                                                    "A vitest test compares this with the site's rule.", "sources": sources.buildability_table(registry)})
    return 0


def command_register(registry: sources.Registry, setting: str) -> int:
    transform_id, transform_row = next(iter(registry.inputs["transforms"].items()))
    command_fetch(registry)
    out_dir = registration.transform_dir(cache_dir(), transform_id, setting)
    print(json.dumps(registration.compute(cache_dir(), transform_row, setting, out_dir), indent=2))
    print("If this setting is to ship, copy its files to the transform's archive directory and update the pins in pipeline-inputs.json in a reviewed diff.")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="atlas_build.py", description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("fetch", help="download and verify every pinned input")
    commands.add_parser("evidence", help="recompute the registration and placement evidence file")
    commands.add_parser("buildability", help="rewrite the per-source buildability file")
    build_parser = commands.add_parser("build", help="build every buildable asset, the manifest, label tables and notices")
    build_parser.add_argument("--allow-dirty", action="store_true", help="build with uncommitted pipeline changes (development only)")
    build_parser.add_argument("--no-sheets", action="store_true", help="skip the review sheets")
    register_parser = commands.add_parser("register", help="compute the registration under one setting into the cache")
    register_parser.add_argument("setting", choices=sorted(registration.SETTINGS))
    arguments = parser.parse_args(argv)
    try:
        registry = sources.load_registry()
        if arguments.command == "fetch":
            return command_fetch(registry)
        if arguments.command == "evidence":
            return command_evidence(registry)
        if arguments.command == "buildability":
            return command_buildability(registry)
        if arguments.command == "register":
            return command_register(registry, arguments.setting)
        return command_build(registry, arguments.allow_dirty, not arguments.no_sheets)
    except PipelineError as error:
        print(f"atlas pipeline: {error}", file=sys.stderr)
        return 1
