#!/usr/bin/env python3
"""
Propagate technique count across the entire codebase.
Updates 135→161 in site pages, docs, data files.
Updates 109→161 in whitepaper drafts.
Updates taxonomy proposal status PROPOSED→ADOPTED.
Syncs SDK registrar copy.
Validates: no stale counts remain after execution.

Usage:
  python3 scripts/propagate-technique-count.py --dry-run
  python3 scripts/propagate-technique-count.py
"""

import re
import sys
import json
import shutil
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).parent.parent
NEW_COUNT = "161"
OLD_COUNTS = ["135", "141"]  # Both stale values to catch
WHITEPAPER_OLD = "109"

# Files to NEVER modify (historical, archived, or derivation log entries that are append-only)
SKIP_FILES = {
    "model/QIF-DERIVATION-LOG.md",  # Historical entries — append only
    "model/logs/NEURORIGHTS-DERIVATION-LOG.md",  # Historical
    "model/research/CROSS-AI-WHITEPAPER-PROMPT.md",  # Historical prompt
    "model/whitepapers/QIF-SCIENTIFIC-PAPER-FUTURE.md",  # Future draft, separate review
    "model/research/QIF-SCIENTIFIC-HYPOTHESES.md",  # Hypotheses doc
    "governance/DECISION-LOG.md",  # Auto-generated, will be regenerated
    "governance/TRANSPARENCY.md",  # Auto-generated
    "src/site/data/kql-tables.json",  # Auto-generated by prebuild
    "src/site/data/qtara-registrar.json",  # Auto-generated copy
}

# Patterns to replace in content files (astro, md, ts, tsx)
CONTENT_PATTERNS = [
    # Exact contextual replacements (135 → 161)
    (r'\b135 techniques\b', f'{NEW_COUNT} techniques'),
    (r'\b135 attack techniques\b', f'{NEW_COUNT} attack techniques'),
    (r'\b135 catalogued attack techniques\b', f'{NEW_COUNT} catalogued attack techniques'),
    (r'\b135 catalogued techniques\b', f'{NEW_COUNT} catalogued techniques'),
    (r'\b135 BCI technique', f'{NEW_COUNT} BCI technique'),
    (r'\b135 BCI attack technique', f'{NEW_COUNT} BCI attack technique'),
    (r'\b135 TARA technique', f'{NEW_COUNT} TARA technique'),
    (r'\b135 TARA threat technique', f'{NEW_COUNT} TARA threat technique'),
    (r'\b135 real threat technique', f'{NEW_COUNT} real threat technique'),
    (r'\b135 threat technique', f'{NEW_COUNT} threat technique'),
    (r'135-technique', f'{NEW_COUNT}-technique'),
    (r'TARA-135_technique', f'TARA-{NEW_COUNT}_technique'),
    (r'\b135 Attack Pattern', f'{NEW_COUNT} Attack Pattern'),
    (r'of 135\b', f'of {NEW_COUNT}'),
    (r'mapping 135\b', f'mapping {NEW_COUNT}'),
    (r'maps 135\b', f'maps {NEW_COUNT}'),
    (r'those 135\b', f'those {NEW_COUNT}'),
    (r'documents 135\b', f'documents {NEW_COUNT}'),
    (r'across 135\b', f'across {NEW_COUNT}'),
    (r'"135"', f'"{NEW_COUNT}"'),  # JSON string values
    (r': 135\b', f': {NEW_COUNT}'),  # JSON numeric values
    (r'Total techniques.*135', f'Total techniques | {NEW_COUNT}'),
    # 141 → 161 (from earlier partial update)
    (r'\b141 techniques\b', f'{NEW_COUNT} techniques'),
    (r'\b141 BCI technique', f'{NEW_COUNT} BCI technique'),
    (r'\b141 TARA technique', f'{NEW_COUNT} TARA technique'),
    (r'of 141\b', f'of {NEW_COUNT}'),
    (r'TARA-141_technique', f'TARA-{NEW_COUNT}_technique'),
]

# Whitepaper patterns (109 → 161)
WHITEPAPER_PATTERNS = [
    (r'\b109 attack technique', f'{NEW_COUNT} attack technique'),
    (r'\b109 technique', f'{NEW_COUNT} technique'),
    (r'109-technique', f'{NEW_COUNT}-technique'),
    (r'across 109\b', f'across {NEW_COUNT}'),
    (r'mapping 109\b', f'mapping {NEW_COUNT}'),
    (r'\b109 cataloged\b', f'{NEW_COUNT} cataloged'),
]

# Files that need the 135→161 content replacement
CONTENT_FILES = [
    "src/pages/index.astro",
    "src/pages/about.astro",
    "src/pages/atlas/tara/ttps.astro",
    "src/pages/atlas/scoring.astro",
    "src/pages/guardrails/index.astro",
    "src/pages/bci/plugin.astro",
    "src/pages/tools/index.astro",
    "src/pages/tools/bci-use-cases.astro",
    "src/pages/tools/intel/index.astro",
    "src/pages/neural-atlas/index.astro",
    "src/pages/governance/ai-security-ethics.astro",
    "src/pages/governance/rights.astro",
    "src/pages/research/neuroethics-landscape.astro",
    "src/pages/research/intel/index.astro",
    "src/pages/research/whitepaper/index.astro",
    "src/data/convergence-data.ts",
    "src/components/bci/BciLandscape.tsx",
    "model/README.md",
    "model/tara-threat/README.md",
    "model/whitepapers/QIF-TRUTH.md",
    "datalake/QIF-DATA-MAPPING.md",
    "docs/tools/bci-plugin-use-cases.md",
    "blogs/2026-03-17-bci-security-plugin-hardrails.md",
    "docs/research/tier3-cross-ai-review.md",
]

WHITEPAPER_FILES = [
    "model/whitepapers/QIF-WHITEPAPER-V8-DRAFT.md",
    "model/whitepapers/QIF-WHITEPAPER.md",
]

TIMELINE_FILE = "src/data/qif-timeline.json"
TAXONOMY_PROPOSAL = "docs/research/tara-domain-taxonomy-proposal.md"


def apply_patterns(content: str, patterns: list) -> tuple[str, int]:
    """Apply regex patterns, return (new_content, change_count)."""
    total = 0
    for pattern, replacement in patterns:
        new_content, n = re.subn(pattern, replacement, content)
        total += n
        content = new_content
    return content, total


def update_file(filepath: Path, patterns: list, dry_run: bool) -> int:
    """Update a single file. Returns number of replacements."""
    if not filepath.exists():
        return 0
    content = filepath.read_text()
    new_content, count = apply_patterns(content, patterns)
    if count > 0 and not dry_run:
        filepath.write_text(new_content)
    return count


def update_timeline(dry_run: bool) -> int:
    """Update qif-timeline.json threat_techniques values."""
    fp = ROOT / TIMELINE_FILE
    if not fp.exists():
        return 0
    content = fp.read_text()
    # Replace "threat_techniques": 135 or "threat_techniques": 141
    new_content = re.sub(
        r'"threat_techniques":\s*(135|141)',
        f'"threat_techniques": {NEW_COUNT}',
        content
    )
    count = len(re.findall(r'"threat_techniques":\s*(135|141)', content))
    if count > 0 and not dry_run:
        fp.write_text(new_content)
    return count


def update_taxonomy_proposal(dry_run: bool) -> bool:
    """Change PROPOSED → ADOPTED in taxonomy proposal."""
    fp = ROOT / TAXONOMY_PROPOSAL
    if not fp.exists():
        print(f"  SKIP: {TAXONOMY_PROPOSAL} not found")
        return False
    content = fp.read_text()
    if "PROPOSED" in content:
        new_content = content.replace(
            "PROPOSED — not yet implemented",
            "ADOPTED — implemented 2026-03-17. Option C (Hybrid): QIF-Txxxx canonical + TARA-{DOMAIN}-{MODE}-{NNN} alias"
        ).replace(
            "Pending cross-review",
            "Adopted after 3-team Quorum review (fact-check, taxonomy-design, security-engineering)"
        )
        if not dry_run:
            fp.write_text(new_content)
        return True
    return False


def sync_sdk_registrar(dry_run: bool) -> bool:
    """Copy primary registrar to SDK data directory."""
    src = ROOT / "datalake" / "qtara-registrar.json"
    dst = ROOT / "datalake" / "qtara" / "src" / "qtara" / "data" / "qtara-registrar.json"
    if not src.exists() or not dst.exists():
        return False
    if not dry_run:
        shutil.copy2(src, dst)
    return True


def validate_no_stale(report: dict) -> bool:
    """Post-flight: verify no stale 135/141 references remain in critical files."""
    ok = True
    stale_files = []
    for pattern_group in [CONTENT_FILES, WHITEPAPER_FILES]:
        for relpath in pattern_group:
            fp = ROOT / relpath
            if not fp.exists():
                continue
            content = fp.read_text()
            # Check for stale counts in technique context
            for old in ["135", "141"]:
                if re.search(rf'\b{old}\s+technique', content) or \
                   re.search(rf'{old}-technique', content) or \
                   re.search(rf'of {old}\b', content) or \
                   re.search(rf'TARA-{old}', content):
                    stale_files.append((relpath, old))
    # Check whitepaper for 109
    for relpath in WHITEPAPER_FILES:
        fp = ROOT / relpath
        if not fp.exists():
            continue
        content = fp.read_text()
        if re.search(r'\b109\s+technique', content) or re.search(r'109-technique', content):
            stale_files.append((relpath, "109"))

    if stale_files:
        print(f"  WARN: {len(stale_files)} stale references remain:")
        for f, old in stale_files[:10]:
            print(f"    {f}: still contains '{old}'")
        ok = False
    else:
        print(f"  PASS: No stale 109/135/141 references in critical files")

    # Verify registrar count
    reg_path = ROOT / "datalake" / "qtara-registrar.json"
    with open(reg_path) as f:
        reg = json.load(f)
    actual = len(reg["techniques"])
    stat = reg.get("statistics", {}).get("total_techniques", 0)
    if actual == int(NEW_COUNT) and stat == int(NEW_COUNT):
        print(f"  PASS: Registrar has {actual} techniques, statistics says {stat}")
    else:
        print(f"  FAIL: Registrar has {actual} techniques, statistics says {stat}, expected {NEW_COUNT}")
        ok = False

    return ok


def run(dry_run=False):
    print(f"{'DRY RUN' if dry_run else 'LIVE'}: Propagate technique count → {NEW_COUNT}")
    print()

    changes = defaultdict(int)

    # 1. Content files (135→161)
    print("=== CONTENT FILES (135/141 → 161) ===")
    for relpath in CONTENT_FILES:
        fp = ROOT / relpath
        n = update_file(fp, CONTENT_PATTERNS, dry_run)
        if n > 0:
            changes[relpath] = n
            print(f"  {relpath}: {n} replacements")
    print()

    # 2. Whitepaper (109→161)
    print("=== WHITEPAPER FILES (109 → 161) ===")
    for relpath in WHITEPAPER_FILES:
        fp = ROOT / relpath
        n = update_file(fp, WHITEPAPER_PATTERNS, dry_run)
        if n > 0:
            changes[relpath] = n
            print(f"  {relpath}: {n} replacements")
    print()

    # 3. Timeline JSON
    print("=== TIMELINE JSON ===")
    n = update_timeline(dry_run)
    if n > 0:
        changes[TIMELINE_FILE] = n
        print(f"  {TIMELINE_FILE}: {n} replacements")
    print()

    # 4. Taxonomy proposal
    print("=== TAXONOMY PROPOSAL STATUS ===")
    if update_taxonomy_proposal(dry_run):
        changes[TAXONOMY_PROPOSAL] = 1
        print(f"  {TAXONOMY_PROPOSAL}: PROPOSED → ADOPTED")
    else:
        print(f"  Already ADOPTED or not found")
    print()

    # 5. SDK sync
    print("=== SDK REGISTRAR SYNC ===")
    if sync_sdk_registrar(dry_run):
        changes["datalake/qtara/src/qtara/data/qtara-registrar.json"] = 1
        print(f"  SDK copy synced from primary registrar")
    print()

    # Summary
    total_changes = sum(changes.values())
    total_files = len(changes)
    print(f"=== SUMMARY: {total_changes} replacements across {total_files} files ===")
    print()

    # Validation (runs even on dry-run to preview)
    if not dry_run:
        print("=== POST-FLIGHT VALIDATION ===")
        ok = validate_no_stale(changes)
        if ok:
            print("\nAll validations passed.")
            print("Next: npm run prebuild && npm run health && npm run build")
        else:
            print("\nWARNINGS detected. Review and fix manually.")
        return ok
    else:
        print("DRY RUN complete. No files modified.")
        # Still run validation on current state to show what would remain
        print("\n=== VALIDATION (current state, pre-changes) ===")
        validate_no_stale(changes)
        return True


if __name__ == "__main__":
    success = run("--dry-run" in sys.argv)
    sys.exit(0 if success else 1)
