/**
 * QifBrainViewer — fsaverage5 cortical surface with blue wireframe aesthetic.
 *
 * Uses the same wireframe + ghost rendering as BrainVisualization.tsx
 * but on anatomically precise fsaverage5 geometry (20,484 vertices).
 * Per-face band LUT enables click-to-identify QIF band regions.
 *
 * Assets: generated by src/scripts/generate-cortical-mesh.py
 *   - /models/fsaverage5-cortex.glb  (combined-hemisphere cortical mesh)
 *   - /models/qif-face-bands.bin     (per-face band LUT for raycasting)
 */

import { Suspense, useState, useRef, useEffect, useCallback } from 'react';
import { Canvas, useFrame, useThree, type ThreeEvent } from '@react-three/fiber';
import { OrbitControls, useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { useWebGLSupport, WebGLFallback } from '../WebGLCheck';
import { HOURGLASS_BANDS } from '../../lib/qif-constants';
import {
  loadFaceBands,
  getBandForFace,
  type CorticalBandId,
} from '../../lib/qif-cortical-data';
import {
  getAllRegions,
  getRegionData,
  getRegionSeverityColor,
  REGION_HOTSPOT_POSITIONS,
} from '../../lib/brain-impact-data';
import type { BrainView } from '../../lib/brain-view-data';

// ═══ Types ═══

interface Props {
  views: BrainView[];
  defaultView?: string;
  externalActiveRegion?: string | null;
  onRegionSelect?: (id: string | null) => void;
  externalViewId?: string;
  onViewChange?: (viewId: string) => void;
  hideViewToggle?: boolean;
}

// ═══ Constants ═══

/** View-specific color palette — matches BrainVisualization.tsx */
const VIEW_COLORS: Record<string, { wire: string; ghost: string; light: string }> = {
  security:   { wire: '#3b82f6', ghost: '#dbeafe', light: '#93c5fd' },
  clinical:   { wire: '#10b981', ghost: '#d1fae5', light: '#6ee7b7' },
  governance: { wire: '#8b5cf6', ghost: '#ede9fe', light: '#c4b5fd' },
};

/** Build region hotspot data from impact chains */
const IMPACT_REGIONS = getAllRegions().map((region) => ({
  regionId: region.regionId,
  regionName: region.regionName,
  bandId: region.bandId,
  position: REGION_HOTSPOT_POSITIONS[region.regionId] ?? [0, 0, 0] as [number, number, number],
  color: getRegionSeverityColor(region.regionId),
  techniqueCount: region.techniques.length,
  totalChains: region.totalChains,
  maxNiss: region.maxNiss,
}));

/** Camera view presets (position, up vector) */
const CAMERA_PRESETS: Record<string, { position: [number, number, number]; up: [number, number, number] }> = {
  left: { position: [-120, 0, 0], up: [0, 1, 0] },
  right: { position: [120, 0, 0], up: [0, 1, 0] },
  top: { position: [0, 120, 0], up: [0, 0, -1] },
  bottom: { position: [0, -120, 0], up: [0, 0, 1] },
  front: { position: [0, 0, 120], up: [0, 1, 0] },
  back: { position: [0, 0, -120], up: [0, 1, 0] },
};

// ═══ Cortical Surface Sub-Components (wireframe + ghost) ═══

function CorticalWireframe({
  wireColor,
  onFaceClick,
}: {
  wireColor: string;
  onFaceClick?: (bandId: CorticalBandId) => void;
}) {
  const { scene } = useGLTF('/models/fsaverage5-cortex.glb');
  const faceBandsRef = useRef<Uint8Array | null>(null);

  useEffect(() => {
    scene.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.material = new THREE.MeshBasicMaterial({
          color: new THREE.Color(wireColor),
          wireframe: true,
          transparent: true,
          opacity: 0.35,
        });
      }
    });
  }, [scene, wireColor]);

  useEffect(() => {
    loadFaceBands()
      .then((bands) => { faceBandsRef.current = bands; })
      .catch((err) => { console.error('Failed to load face bands:', err); });
  }, []);

  const handleClick = useCallback((event: ThreeEvent<MouseEvent>) => {
    if (!onFaceClick || !faceBandsRef.current) return;
    event.stopPropagation();
    const faceIndex = event.faceIndex;
    if (faceIndex === undefined || faceIndex === null) return;
    const bandId = getBandForFace(faceIndex);
    if (bandId) onFaceClick(bandId);
  }, [onFaceClick]);

  return <primitive object={scene} onClick={handleClick} />;
}

function CorticalGhost({ ghostColor }: { ghostColor: string }) {
  const { scene } = useGLTF('/models/fsaverage5-cortex.glb');
  const ghostScene = useRef<THREE.Group | null>(null);

  useEffect(() => {
    const cloned = scene.clone(true);
    cloned.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.material = new THREE.MeshBasicMaterial({
          color: new THREE.Color(ghostColor),
          transparent: true,
          opacity: 0.12,
          side: THREE.DoubleSide,
        });
      }
    });
    ghostScene.current = cloned;
  }, [scene, ghostColor]);

  if (!ghostScene.current) return null;
  return <primitive object={ghostScene.current} />;
}

// ═══ Region Hotspot Sub-Component ═══

function RegionHotspot({
  regionId,
  position,
  color,
  techniqueCount,
  isActive,
  onHover,
  onClick,
}: {
  regionId: string;
  position: [number, number, number];
  color: string;
  techniqueCount: number;
  isActive: boolean;
  onHover: (id: string | null) => void;
  onClick: (id: string) => void;
}) {
  const coreRef = useRef<THREE.Mesh>(null);
  const glowRef = useRef<THREE.Mesh>(null);
  const ringRef = useRef<THREE.Mesh>(null);

  // Scale hotspot by technique count (more techniques = bigger dot)
  const baseSize = 2.0 + Math.min(techniqueCount / 15, 2.0);

  useFrame((state) => {
    const t = state.clock.elapsedTime;
    if (coreRef.current) {
      const scale = isActive
        ? 1.0 + Math.sin(t * 3) * 0.25
        : 1.0 + Math.sin(t * 2 + position[0]) * 0.1;
      coreRef.current.scale.setScalar(scale);
    }
    if (glowRef.current) {
      const glowScale = isActive
        ? 1.3 + Math.sin(t * 2.5) * 0.15
        : 1.0 + Math.sin(t * 1.5 + position[1]) * 0.08;
      glowRef.current.scale.setScalar(glowScale);
      (glowRef.current.material as THREE.MeshBasicMaterial).opacity =
        isActive ? 0.25 + Math.sin(t * 3) * 0.1 : 0.12;
    }
    if (ringRef.current) {
      ringRef.current.rotation.z = t * 0.8;
      const ringScale = isActive ? 1.3 : 1.0;
      ringRef.current.scale.setScalar(ringScale);
    }
  });

  return (
    <group position={position} renderOrder={10}>
      {/* Glow sphere */}
      <mesh ref={glowRef} renderOrder={10}>
        <sphereGeometry args={[baseSize * 1.0, 16, 16]} />
        <meshBasicMaterial
          color={color}
          transparent
          opacity={0.12}
          depthWrite={false}
          depthTest={false}
        />
      </mesh>
      {/* Core sphere (clickable) */}
      <mesh
        ref={coreRef}
        renderOrder={11}
        onPointerOver={(e) => { e.stopPropagation(); onHover(regionId); }}
        onPointerOut={() => onHover(null)}
        onClick={(e) => { e.stopPropagation(); onClick(regionId); }}
      >
        <sphereGeometry args={[baseSize * 0.5, 16, 16]} />
        <meshBasicMaterial
          color={color}
          transparent
          opacity={isActive ? 0.85 : 0.55}
          depthWrite={false}
          depthTest={false}
        />
      </mesh>
      {/* Ring */}
      <mesh ref={ringRef} renderOrder={10}>
        <ringGeometry args={[baseSize * 0.65, baseSize * 0.75, 32]} />
        <meshBasicMaterial
          color={color}
          transparent
          opacity={isActive ? 0.5 : 0.2}
          side={THREE.DoubleSide}
          depthWrite={false}
          depthTest={false}
        />
      </mesh>
    </group>
  );
}

// ═══ Band Legend ═══

function BandLegend({
  activeBand,
  onBandClick,
}: {
  activeBand: string | null;
  onBandClick: (id: string | null) => void;
}) {
  // Show only neural bands (N7-N1)
  const neuralBands = HOURGLASS_BANDS.filter((b) => b.zone === 'neural');

  return (
    <div className="absolute bottom-3 left-3 flex flex-col gap-0.5 bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm rounded-lg px-2.5 py-2 text-xs shadow-sm border border-slate-200 dark:border-slate-700">
      <span className="text-[10px] font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-0.5">
        QIF Bands
      </span>
      {neuralBands.map((band) => {
        const isActive = activeBand === band.id;
        const isCortical = band.id === 'N7' || band.id === 'N6';
        return (
          <button
            key={band.id}
            onClick={() => onBandClick(isActive ? null : band.id)}
            className={`flex items-center gap-1.5 px-1 py-0.5 rounded transition-colors text-left ${
              isActive
                ? 'bg-slate-100 dark:bg-slate-800'
                : 'hover:bg-slate-50 dark:hover:bg-slate-800/50'
            }`}
          >
            <span
              className="w-2.5 h-2.5 rounded-sm flex-shrink-0"
              style={{
                backgroundColor: band.color,
                opacity: isCortical ? 1 : 0.5,
              }}
            />
            <span className={`${isActive ? 'font-medium' : ''} ${isCortical ? '' : 'text-slate-400 dark:text-slate-500'}`}>
              {band.id} {band.name}
            </span>
          </button>
        );
      })}
    </div>
  );
}

// ═══ Camera Preset Buttons ═══

function CameraPresets({
  onSelect,
}: {
  onSelect: (preset: string) => void;
}) {
  const presets = [
    { id: 'left', label: 'L' },
    { id: 'right', label: 'R' },
    { id: 'top', label: 'T' },
    { id: 'front', label: 'F' },
    { id: 'back', label: 'B' },
  ];

  return (
    <div className="absolute top-3 right-3 flex gap-1">
      {presets.map((p) => (
        <button
          key={p.id}
          onClick={() => onSelect(p.id)}
          className="w-6 h-6 rounded bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm text-[10px] font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-700 transition-colors flex items-center justify-center"
          title={p.id}
        >
          {p.label}
        </button>
      ))}
    </div>
  );
}

// ═══ Camera Controller (responds to preset changes) ═══

function CameraController({
  preset,
  onPresetApplied,
}: {
  preset: string | null;
  onPresetApplied: () => void;
}) {
  const { camera } = useThree();

  useEffect(() => {
    if (!preset || !(preset in CAMERA_PRESETS)) return;
    const { position, up } = CAMERA_PRESETS[preset];
    camera.position.set(...position);
    camera.up.set(...up);
    camera.lookAt(0, 0, 0);
    onPresetApplied();
  }, [preset, camera, onPresetApplied]);

  return null;
}

// ═══ Technique Panel (slides in when a region hotspot is clicked) ═══

const SEVERITY_COLORS: Record<string, string> = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#94a3b8',
};

function TechniquePanel({
  regionId,
  onClose,
}: {
  regionId: string;
  onClose: () => void;
}) {
  const data = getRegionData(regionId);
  if (!data) return null;

  return (
    <div className="absolute top-0 right-0 h-full w-[320px] bg-white/95 dark:bg-slate-900/95 backdrop-blur-sm border-l border-slate-200 dark:border-slate-700 overflow-y-auto">
      {/* Header */}
      <div className="sticky top-0 bg-white/95 dark:bg-slate-900/95 backdrop-blur-sm px-3 py-2.5 border-b border-slate-200 dark:border-slate-700 z-10">
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-1.5">
              <span
                className="w-2.5 h-2.5 rounded-full"
                style={{ backgroundColor: getRegionSeverityColor(regionId) }}
              />
              <span className="font-semibold text-sm text-slate-900 dark:text-white">
                {data.regionName}
              </span>
            </div>
            <span className="text-[10px] text-slate-400">
              {data.bandId} {data.bandName} · {data.techniques.length} techniques · {data.totalChains} impact chains
            </span>
          </div>
          <button
            onClick={onClose}
            className="w-6 h-6 flex items-center justify-center rounded hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-400 text-sm"
          >
            ×
          </button>
        </div>
        {/* Severity bar */}
        <div className="flex gap-1 mt-1.5">
          {Object.entries(data.severityCounts).map(([sev, count]) => (
            <span
              key={sev}
              className="text-[9px] px-1.5 py-0.5 rounded-full"
              style={{
                backgroundColor: `${SEVERITY_COLORS[sev] ?? '#94a3b8'}20`,
                color: SEVERITY_COLORS[sev] ?? '#94a3b8',
              }}
            >
              {count} {sev}
            </span>
          ))}
        </div>
      </div>

      {/* Technique list */}
      <div className="divide-y divide-slate-100 dark:divide-slate-800">
        {data.techniques.map((tech) => (
          <a
            key={tech.id}
            href={tech.href}
            className="block px-3 py-2 hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors group"
          >
            <div className="flex items-center gap-1.5 mb-0.5">
              <span
                className="w-1.5 h-1.5 rounded-full flex-shrink-0"
                style={{ backgroundColor: SEVERITY_COLORS[tech.severity] ?? '#94a3b8' }}
              />
              <span className="font-mono text-[10px] text-slate-400 group-hover:text-slate-600 dark:group-hover:text-slate-300">
                {tech.id}
              </span>
              <span className="text-[10px] text-slate-300 dark:text-slate-600">·</span>
              <span className="text-[10px] font-medium" style={{ color: SEVERITY_COLORS[tech.severity] }}>
                {tech.nissScore.toFixed(1)}
              </span>
            </div>
            <div className="text-xs font-medium text-slate-700 dark:text-slate-200 group-hover:text-blue-600 dark:group-hover:text-blue-400">
              {tech.name}
            </div>
            {tech.dsmOutcomes.length > 0 && (
              <div className="text-[10px] text-slate-400 mt-0.5 truncate">
                → {tech.dsmOutcomes.map((d) => d.name).join(', ')}
              </div>
            )}
            {tech.pathways.length > 0 && (
              <div className="text-[10px] text-slate-400 truncate">
                via {tech.pathways[0]}
              </div>
            )}
          </a>
        ))}
      </div>
    </div>
  );
}

// ═══ Scene (assembles all 3D elements) ═══

function BrainScene({
  viewId,
  activeBand,
  showSubcortical,
  cameraPreset,
  onCameraPresetApplied,
  onBandSelect,
}: {
  viewId: string;
  activeBand: string | null;
  showSubcortical: boolean;
  cameraPreset: string | null;
  onCameraPresetApplied: () => void;
  onBandSelect: (id: string | null) => void;
}) {
  const colors = VIEW_COLORS[viewId] ?? VIEW_COLORS.security;

  const handleFaceClick = useCallback(
    (bandId: CorticalBandId) => {
      onBandSelect(activeBand === bandId ? null : bandId);
    },
    [activeBand, onBandSelect],
  );

  const handleSubcorticalHover = useCallback(
    (_id: string | null) => {
      // Hover preview — Phase 2
    },
    [],
  );

  const handleSubcorticalClick = useCallback(
    (id: string) => {
      onBandSelect(activeBand === id ? null : id);
    },
    [activeBand, onBandSelect],
  );

  return (
    <>
      <ambientLight intensity={0.5} />
      <directionalLight position={[10, 10, 5]} intensity={1} />
      <directionalLight position={[-5, -5, 10]} intensity={0.4} color={colors.light} />

      <Suspense fallback={null}>
        <CorticalGhost ghostColor={colors.ghost} />
        <CorticalWireframe
          wireColor={colors.wire}
          onFaceClick={handleFaceClick}
        />

        {showSubcortical && IMPACT_REGIONS.map((region) => (
          <RegionHotspot
            key={region.regionId}
            regionId={region.regionId}
            position={region.position as [number, number, number]}
            color={region.color}
            techniqueCount={region.techniqueCount}
            isActive={activeBand === region.regionId}
            onHover={handleSubcorticalHover}
            onClick={handleSubcorticalClick}
          />
        ))}
      </Suspense>

      <CameraController
        preset={cameraPreset}
        onPresetApplied={onCameraPresetApplied}
      />

      <OrbitControls
        enablePan={false}
        enableZoom={true}
        enableRotate={true}
        minDistance={80}
        maxDistance={250}
        target={[0, 0, 0]}
      />
    </>
  );
}

// ═══ Main Component ═══

useGLTF.preload('/models/fsaverage5-cortex.glb');

export default function QifBrainViewer({
  views,
  defaultView,
  externalActiveRegion,
  onRegionSelect,
  externalViewId,
  onViewChange,
  hideViewToggle,
}: Props) {
  const [internalViewId, setInternalViewId] = useState(defaultView ?? views[0]?.id ?? 'security');
  const [activeBand, setActiveBand] = useState<string | null>(null);
  const [showSubcortical, setShowSubcortical] = useState(true);
  const [cameraPreset, setCameraPreset] = useState<string | null>(null);
  const webglSupported = useWebGLSupport();

  const activeViewId = externalViewId ?? internalViewId;

  const handleViewChange = useCallback((viewId: string) => {
    if (onViewChange) onViewChange(viewId);
    else setInternalViewId(viewId);
  }, [onViewChange]);

  const handleBandSelect = useCallback((id: string | null) => {
    setActiveBand(id);
    if (onRegionSelect) onRegionSelect(id);
  }, [onRegionSelect]);

  const handleCameraPreset = useCallback((preset: string) => {
    setCameraPreset(preset);
  }, []);

  const handleCameraPresetApplied = useCallback(() => {
    setCameraPreset(null);
  }, []);

  if (!webglSupported) {
    return <WebGLFallback feature="QIF cortical visualization" />;
  }

  return (
    <div className="relative w-full aspect-[4/3] rounded-xl overflow-hidden bg-slate-950 border border-slate-200 dark:border-slate-700">
      <Canvas
        camera={{
          position: [0, 0, 160],
          fov: 45,
          near: 1,
          far: 500,
        }}
        gl={{ antialias: true, alpha: false }}
        dpr={[1, 2]}
      >
        <color attach="background" args={['#0f172a']} />
        <BrainScene
          viewId={activeViewId}
          activeBand={activeBand}
          showSubcortical={showSubcortical}
          cameraPreset={cameraPreset}
          onCameraPresetApplied={handleCameraPresetApplied}
          onBandSelect={handleBandSelect}
        />
      </Canvas>

      {/* Technique panel (slides in from right) */}
      {activeBand && getRegionData(activeBand) && (
        <TechniquePanel
          regionId={activeBand}
          onClose={() => handleBandSelect(null)}
        />
      )}

      {/* Camera presets */}
      <CameraPresets onSelect={handleCameraPreset} />

      {/* Band legend */}
      <BandLegend activeBand={activeBand} onBandClick={handleBandSelect} />

      {/* Controls row */}
      <div className="absolute bottom-3 right-3 flex items-center gap-2">
        {/* Subcortical toggle */}
        <button
          onClick={() => setShowSubcortical(!showSubcortical)}
          className={`text-[10px] px-2 py-1 rounded backdrop-blur-sm border transition-colors ${
            showSubcortical
              ? 'bg-white/80 dark:bg-slate-800/80 border-slate-300 dark:border-slate-600 text-slate-700 dark:text-slate-200'
              : 'bg-white/40 dark:bg-slate-900/40 border-slate-200 dark:border-slate-700 text-slate-400 dark:text-slate-500'
          }`}
        >
          {showSubcortical ? 'Subcortical ON' : 'Subcortical OFF'}
        </button>

        {/* View toggle (if not hidden) */}
        {!hideViewToggle && views.length > 1 && (
          <div className="flex rounded overflow-hidden border border-slate-200 dark:border-slate-700 backdrop-blur-sm">
            {views.map((view) => (
              <button
                key={view.id}
                onClick={() => handleViewChange(view.id)}
                className={`text-[10px] px-2 py-1 transition-colors ${
                  activeViewId === view.id
                    ? 'bg-white/80 dark:bg-slate-800/80 text-slate-700 dark:text-slate-200 font-medium'
                    : 'bg-white/40 dark:bg-slate-900/40 text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300'
                }`}
              >
                {view.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
